name: Remote SSH Deployment
on:
  push:
    branches:
      - stage  # or your default branch

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/khaitun/Donate-Website-Dev
            git pull origin stage
            echo "Deploy completed at $(date)" >> deploy.log
            # Add your additional deployment commands here
            # For example:
            npm install -f
            npm run build
            pm2 start
